# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0

# Runs tests and computes the code coverage

name: coverage
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  measure_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get GOVERSION content
        id: goversion
        run: echo ::set-output name=version::$(cat GOVERSION)

      - uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: "${{ steps.goversion.outputs.version }}"
          cache-key-suffix: "-coverage-${{ steps.goversion.outputs.version }}"

      - run: go test -short -race -tags shaping -coverprofile=l3afd.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: l3afd.cov
          parallel: true

  finish_measuring_coverage:
    needs: measure_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true